## Задания

**Задача 1.**

Даны четыре действительных числа: x1, y1, x2, y2. Напишите функцию distance(x1, y1, x2, y2), вычисляющая евклидово расстояние ( https://ru.wikipedia.org/wiki/%D0%95%D0%B2%D0%BA%D0%BB%D0%B8%D0%B4%D0%BE%D0%B2%D0%B0_%D0%BC%D0%B5%D1%82%D1%80%D0%B8%D0%BA%D0%B0 ) между точкой (x1,y1) и (x2,y2).

In [185]:
from math import sqrt


def distance(x1, y1, x2, y2) -> float:
  return sqrt((x2 - x1) ** 2 + (y2 -  y1) ** 2)


print(distance(1, 4, 3, 8))

4.47213595499958


**Задача 2.**

Написать функцию season(month), принимающую 1 аргумент — номер месяца (от 1 до 12), которая присваивает глобальной переменной s время года, которому этот месяц принадлежит (зима, весна, лето или осень).

In [184]:
s = None


def season(month):
    global s
    
    a = month % 12 + 1
    if a < 4:
        s = "Winter"
    elif a < 7:
        s = "Spring"
    elif a < 10:
        s = "Summer"
    else:
        s = "Fall"


season(12)
print(s)

Winter


**Задача 3.**

Написать функцию is_prime, принимающую 1 аргумент — число от 0 до 1000, и возвращающую True, если оно простое, и False - иначе.

In [178]:
def is_prime(number):
  if number == 1:
    return False

  for div in range(2, number // 2 + 1):
    if number % div == 0:
      return False

  return True

print(is_prime(551))

False


**Задача 4.**

Написать функцию reverse_list(lst), которая принимает в качестве аргумента список и возвращаем его в перевернутом виде.

Например,
- исходный список:  8, 1, 0, 4
- полученный список: 4, 0, 1, 8

Использовать встроенные функции Python нельзя. 

In [177]:
def reverse_list(lst):
  return lst[::-1]

print(reverse_list([1, 2, 3, 4]))

[4, 3, 2, 1]


**Задача 5.**

Распечатайте с 4 по 8 символ фразы "Привет мир!" приведенные к верхнему регистру.

In [5]:
hello_world = 'Привет мир!'
print(hello_world[3:9].upper())

ВЕТ МИ


**Задача 6.**

Напишите код, который все элементы массива x с нечетными индексами переставит в обратном порядке.

Т.е. если x = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], то код должен получать [0, 9, 2, 7, 4, 5, 6, 3, 8, 1]

In [176]:
x = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
is_odd = (len(x) % 2 != 0)
for i in range(1, len(x) // 2 + 1, 2):
    tmp = x[len(x) - i - is_odd]
    x[len(x) - i - is_odd]= x[i]
    x[i] = tmp

print(x)

[0, 9, 2, 7, 4, 5, 6, 3, 8, 1]


**Задача 7.**

Напишите цикл, который выводит все числа от 0 до 500, делящиеся на 7, если в них есть цифра 8.

In [9]:
number = 8
while True:
  if number > 500:
    break
  if number % 7 == 0:
    print(number)
  number += 10

28
98
168
238
308
378
448


**Задача 8.**

На вход функция more_than_five(lst) получает список из целых чисел. 
Результатом работы функции должен стать новый список, в котором содержатся только те числа, которые больше 10 по модулю.

In [ ]:
def more_than_five(lst):
  return list(filter(lambda number : abs(number) > 10, lst))

# Задания

In [10]:
import numpy as np

**Задача 1.**

Создать матрицу размером `10х10` с 0 внутри, и 1 на границах. Например для `3х3`.

```
1 1 1
1 0 1
1 1 1
```

In [11]:
matrix = np.ones((10, 10))
matrix[1:-1, 1:-1] = 0
print(matrix)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


**Задача 2.**

Создать 5x5 матрицу с 1,2,3,4 над диагональю. Все остальные элементы - 0.

In [15]:
matrix = np.diag(np.arange(1, 5), k=1)
print(matrix)

[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


**Задача 3.**

Создайте случайную матрицу и вычтите из каждой строки среднее.

In [16]:
matrix = np.random.randn(4, 3)
print(matrix, end='\n\n')

for row in matrix:
  print('Среднее строки =', np.mean(row))
  row -= np.mean(row)

print('\n', matrix)

[[ 0.59379307 -2.04917957  0.5551507 ]
 [-1.17844135 -0.67336555  0.95944203]
 [-0.34341983 -0.7909957  -1.13672132]
 [ 1.69631196  0.83427238  0.25354353]]

Среднее строки = -0.30007860201281117
Среднее строки = -0.2974549572405913
Среднее строки = -0.7570456159560065
Среднее строки = 0.928042622567029

 [[ 0.89387167 -1.74910097  0.8552293 ]
 [-0.88098639 -0.37591059  1.25689698]
 [ 0.41362579 -0.03395008 -0.3796757 ]
 [ 0.76826934 -0.09377025 -0.67449909]]



**Задача 4.**

Написать функцию, принимающую на вход массив и меняющую знак у элементов, значения которых между 3 и 8. Протестировать на нескольких заданных вами массивах.

In [17]:
def switch_sign(arr):
  arr[(arr > 3) & (arr < 8)] *= -1

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
switch_sign(a)
b = np.array([10, 8, 2, 6, 4, 9, 2, 3, 4])
switch_sign(b)

print(a, end='\n\n')
print(b)

[ 1  2  3 -4 -5 -6 -7  8  9 10]

[10  8  2 -6 -4  9  2  3 -4]


**Задача 4.**

Написать функцию, принимающую на вход массив и вычитающую среднее из каждой строки в матрице. Протестировать на нескольких заданных вами примерах.

In [18]:
def rows_minus_mean(matrix):
  for row in matrix:
    row -= np.mean(row)

a = np.array([
    [1., 2., 3.],
    [7., 8., 9.]
])

b = np.array([
    [7., 25., 3.],
    [7., 9., 2.],
    [12., 3., 4.]
])

rows_minus_mean(a)
rows_minus_mean(b)

print(a, end='\n\n')
print(b)

[[-1.  0.  1.]
 [-1.  0.  1.]]

[[-4.66666667 13.33333333 -8.66666667]
 [ 1.          3.         -4.        ]
 [ 5.66666667 -3.33333333 -2.33333333]]


**Задача 5.**

Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением.

In [19]:
v = np.arange(1, 6)

v_len = len(v)
new_v = np.zeros(v_len + (v_len - 1) * 3, int)

new_v[::4] = v

print(new_v)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


**Задача 6.**


Написать функцию, принимающую на вход матрицу MxN и меняющую 2 любые строки в матрице. Протестировать на нескольких заданных вами примерах.

In [57]:
def switch_rows(matrix):
  row1 = np.random.randint(len(matrix))
  row2 = np.random.randint(len(matrix))
  while row2 == row1:
    row2 = np.random.randint(len(matrix))

  print(f'Switching rows {row1} and {row2}\n')
  
  matrix[[row1, row2]] = matrix[[row2, row1]]

matrix = np.random.randint(20, size=(5, 3))
print(matrix, '\n')
switch_rows(matrix)
print(matrix)

[[ 9  2 18]
 [ 9  8  2]
 [ 2 17  9]
 [ 8  5 17]
 [ 1 13 11]] 

Switching rows 1 and 3

[[ 9  2 18]
 [ 8  5 17]
 [ 2 17  9]
 [ 9  8  2]
 [ 1 13 11]]


**Задача 7.**


Написать функцию, принимающую на вход одномерный массив и возвращающую наиболее частое значение в массиве и частоту его встречи. Протестировать на нескольких заданных вами примерах.

In [58]:
def number_freq(lst):
  values, counts = np.unique(lst, return_counts=True)
  ind_max = np.argmax(counts)
  return [values[ind_max], counts[ind_max]]

a = np.array([1, 1, 2, 3, 7, 7, 7, 8, 2, 7, 9, 1, 5])
print(number_freq(a))

[7, 4]


**Задача 8.** 

Написать функцию, принимающую на вход  массив 16x16 и считающую сумму по блокам 4x4. Протестировать на нескольких заданных вами примерах.

In [59]:
def sixteen_by_sixteen(matrix):
  for i in range(2):
    for j in range(2):
      tmp = matrix[i*4:(i+1)*4, j*4:(j+1)*4]
      print(tmp, '\n', np.sum(tmp), end='\n\n')

m = np.random.randint(10, size=(16, 16))
print(m, end='\n\n')
sixteen_by_sixteen(m)

[[7 6 0 7 5 9 7 0 9 8 4 8 7 7 4 3]
 [8 3 6 3 0 0 3 4 4 3 3 5 9 0 7 9]
 [7 4 5 6 9 4 9 5 0 8 8 8 8 5 5 1]
 [9 6 7 0 6 6 6 7 3 8 9 8 1 8 2 6]
 [2 3 3 3 4 8 4 8 7 6 3 3 4 0 5 5]
 [5 5 5 1 1 5 2 8 0 8 7 6 1 4 5 8]
 [0 0 3 7 1 5 7 6 8 0 1 4 6 7 4 7]
 [2 9 5 2 6 5 3 0 7 7 9 8 1 1 3 5]
 [8 0 6 7 9 3 6 2 9 5 3 3 3 9 5 1]
 [6 9 9 8 8 4 9 6 1 5 3 1 5 3 9 8]
 [0 8 1 2 7 7 6 3 7 4 2 2 6 0 3 7]
 [7 5 0 1 8 7 0 8 2 0 6 3 7 4 4 1]
 [4 5 9 1 4 7 7 2 8 9 9 8 4 9 7 0]
 [4 9 6 6 6 3 8 0 7 7 4 6 8 0 4 0]
 [0 3 1 4 7 2 9 7 1 7 8 0 6 0 4 2]
 [5 7 1 2 2 5 7 6 9 1 0 3 0 6 2 2]]

[[7 6 0 7]
 [8 3 6 3]
 [7 4 5 6]
 [9 6 7 0]] 
 84

[[5 9 7 0]
 [0 0 3 4]
 [9 4 9 5]
 [6 6 6 7]] 
 80

[[2 3 3 3]
 [5 5 5 1]
 [0 0 3 7]
 [2 9 5 2]] 
 55

[[4 8 4 8]
 [1 5 2 8]
 [1 5 7 6]
 [6 5 3 0]] 
 73



**Задача 9.**

Написать функцию, принимающую на вход матрицу и возвращающую n наибольших значений в массиве. n вводится с клавиатуры. Протестировать на нескольких заданных вами примерах.

In [60]:
def max_values(matrix, n):
  ind = np.argpartition(a, -n)[-n:]
  return matrix[ind]

n = int(input('Enter amount of big values you want to find: '))
a = np.random.randint(20, size=n+4)
print(a)

m = max_values(a, n)
print(m)

Enter amount of big values you want to find: 6
[ 8 18 17  5  3 19 19 11 12  6]
[11 12 17 18 19 19]


**Задача 10.**

Написать функцию, принимающую на вход 10x3 матрица и находящую строки из неравных значений (например [2,2,3]). Протестировать на нескольких заданных вами примерах.

In [68]:
def find_unequal(matrix):
  is_equal = np.logical_and.reduce(matrix[:,1:] == matrix[:,:-1], axis=1)
  return matrix[~is_equal]


matrix = np.random.randint(3, size=(10, 3))
print(matrix, end='\n\n')
unequalities = find_unequal(matrix)
print(unequalities)


[[0 2 1]
 [2 1 2]
 [2 0 0]
 [2 0 1]
 [1 2 2]
 [1 2 1]
 [0 0 1]
 [2 0 1]
 [1 1 2]
 [2 2 2]]

[[0 2 1]
 [2 1 2]
 [2 0 0]
 [2 0 1]
 [1 2 2]
 [1 2 1]
 [0 0 1]
 [2 0 1]
 [1 1 2]]


**Задача 11.**

Написать функцию, принимающую на вход двумерный массив и находящую все различные строки. Протестировать на нескольких заданных вами примерах.

In [86]:
def find_unique_rows(matrix):
  return np.unique(matrix, axis=0)
  

matrix = np.random.randint(3, size=(5, 5))
print(matrix, end='\n\n')
unique_rows = find_unique_rows(matrix)
print(unique_rows, end='\n\n')

matrix = np.array([
    [1, 3, 4],
    [1, 3, 4],
    [7, 8, 9],
    [5, 6, 9],
    [1, 3, 4]
])
print(matrix, end='\n\n')
unique_rows = find_unique_rows(matrix)
print(unique_rows)

[[2 0 0 2 0]
 [2 1 1 1 2]
 [1 0 2 2 0]
 [1 0 0 0 0]
 [1 1 2 1 2]]

[[1 0 0 0 0]
 [1 0 2 2 0]
 [1 1 2 1 2]
 [2 0 0 2 0]
 [2 1 1 1 2]]

[[1 3 4]
 [1 3 4]
 [7 8 9]
 [5 6 9]
 [1 3 4]]

[[1 3 4]
 [5 6 9]
 [7 8 9]]


**Задача 12.**

Написать функцию, принимающую на вход два вектора одинакого размера и считающую расстояние между векторами. Протестировать на нескольких заданных вами примерах.

In [88]:
def distance_between(vector1, vector2):
  return np.linalg.norm(vector1 - vector2)

vect1 = np.random.randint(5, size=3)
vect2 = np.random.randint(5, size=3)

print(f'Vector 1: {vect1}\nVector 2: {vect2}\n')
dist = distance_between(vect1, vect2)
print(f'Distance between vector1 and vector2: {dist}')

Vector 1: [4 1 0]
Vector 2: [1 1 4]

Distance between vector1 and vector2: 5.0


**Задача 13.**

Написать функцию, принимающую на вход два вектора одинакого размера и находящую косинус угла между векторами. Протестировать на нескольких заданных вами примерах.

In [94]:
def get_cos(vector1, vector2):
  dot = np.dot(vector1, vector2)
  v1_length = np.linalg.norm(vector1)
  v2_length = np.linalg.norm(vector2)

  return dot / (v1_length * v2_length)

vect1 = np.random.randint(5, size=3)
vect2 = np.random.randint(5, size=3)
print(f'Vector 1: {vect1}\nVector 2: {vect2}\n')

cos = get_cos(vect1, vect2)
print(f'Cos between vector1 and vector2: {cos}')

Vector 1: [4 4 2]
Vector 2: [0 3 4]

Cos between vector1 and vector2: 0.6666666666666666


**Задача 14.**

Написать функцию, принимающую на вход вектор A содержит float числа как больше, так и меньше нуля.

Функция должна округлить их до целых и результат записать в глобальную переменную Z. Округление должно быть "от нуля", т.е.:

- положительные числа округляем всегда вверх до целого
- отрицательные числа округляем всегда вниз до целого
- 0 остаётся 0

 Протестировать на нескольких заданных вами примерах.


In [123]:
Z = None


def round_vector(vector):
  global Z
  Z = np.where(vector < 0, 
              np.floor(vector), 
              np.where(vector > 0, np.ceil(vector), vector))


A = np.random.randn(4) * 10
print(A)
round_vector(A)
print(Z)

[-10.93121061  -3.10622667  -1.80414747  11.39808   ]
[-11.  -4.  -2.  12.]


**Задача 15.**

Написать функцию, принимающую на вход 2 вектора целых чисел A и B.

Функция должна находить числа, встречающиеся в обоих векторах и добавлять их по возрастанию в глобальную переменную - вектор Z.

*Если пересечений нет, то вектор Z будет пустым*.

 Протестировать на нескольких заданных вами примерах.

In [163]:
Z = None


def same_values(vector1, vector2):
  global Z
  Z = np.intersect1d(vector1, vector2)

vect1 = np.random.randint(10, size=8)
vect2 = np.random.randint(10, size=8)

print(f'Vector 1: {vect1}\nVector 2: {vect2}\n')

same_values(vect1, vect2)

print(Z)

Vector 1: [7]
Vector 2: [6]

[]


**Задача 16.**

Написать функцию, принимающую на вход вектор и возвращающую максимальный элемент в векторе среди элементов, перед которыми стоит 0. 

Например для:

`x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])`

Ответ:
5

In [148]:
def max_after_zero(vector):
  zeros = (vector == 0)
  return np.max(vector[1:][zeros[:-1]])


x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
result = max_after_zero(x)
print(result)

5


**Задача 17.**

Написать функцию, принимающую на вход матрицу 5х3 и считающую длину каждого вектора в матрице (строка) и ищущую самый длинный вектор, вернуть его координаты и длину.

Как выглядит матрица:

```   
     | x | y | z |
     | 1 | 2 | 3 |
     | 3 | 4 | 1 |
     | ...       |
```

In [175]:
def longest_vector(matrix):
  norms = np.linalg.norm(matrix, axis=1)
  max_length = norms.max()
  max_vector = matrix[np.where(norms == max_length)[0][0]]

  return max_vector, max_length


matrix = np.random.randint(20, size=(5, 3))
print(matrix, '\n')

result = longest_vector(matrix)
print(f'The longest vector: {result[0]}\nIts length: {result[1]}')

[[ 0  6  5]
 [ 0  0  1]
 [ 6 13  7]
 [16 13  5]
 [ 4  9  3]] 

The longest vector: [16 13  5]
Its length: 21.213203435596427
